
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Help(object):
    def setupUi(self, Help):
        Help.setObjectName("Help")
        Help.resize(863, 648)
        self.label = QtWidgets.QLabel(Help)
        self.label.setGeometry(QtCore.QRect(10, 10, 251, 101))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Help)
        self.label_2.setGeometry(QtCore.QRect(10, 120, 381, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.widget = QtWidgets.QWidget(Help)
        self.widget.setGeometry(QtCore.QRect(10, 201, 771, 401))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_5 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_4 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_6 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)

        self.retranslateUi(Help)
        QtCore.QMetaObject.connectSlotsByName(Help)

    def retranslateUi(self, Help):
        _translate = QtCore.QCoreApplication.translate
        Help.setWindowTitle(_translate("Help", "Form"))
        self.label.setText(_translate("Help", "Help Menu\n"
"Video Encoding\n"
"Ervin Halimsurya - 1806195173\n"
"Jonathan Richard - 1806147930"))
        self.label_2.setText(_translate("Help", "Aplikasi ini merupakan simulasi encoding video. \n"
"Cara menggunakannya adalah sebagai berikut:"))
        self.label_3.setText(_translate("Help", "1. Menentukan video yang ingin di encode"))
        self.label_5.setText(_translate("Help", "2. Memilih folder tujuan file hasil encode akan disimpan dan memasukkan nama file hasil encode"))
        self.label_4.setText(_translate("Help", "3. Setelah melakukan tahap 1 dan dua, dapat dilakukan encoding"))
        self.label_6.setText(_translate("Help", "4. Memilih folder untuk menyimpan hasil video dan memberi nama video"))
        self.label_7.setText(_translate("Help", "5. Setelah melakukan tahap 1, 2, 3, dan 4, pross decode dapat dilakukan."))
        self.label_8.setText(_translate("Help", "6. Ukuran video hasil decoded dapat dilihat setelah proses decode selesai dan tombol play ditekan."))
        self.label_9.setText(_translate("Help", "* Original video size merupakan ukuran video asli setelah di decompress menggunakan opencv"))
        self.label_10.setText(_translate("Help", "* Ukuran file hasil encoded dapat dilihat setelah proses encoding selesai"))
        self.label_11.setText(_translate("Help", "* Custom quantization matrix tidak boleh memiliki nilai 0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Help = QtWidgets.QWidget()
    ui = Ui_Help()
    ui.setupUi(Help)
    Help.show()
    sys.exit(app.exec_())
