from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QStyle
from PyQt5.QtCore import QSize,Qt

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
       
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1378, 866)
        btnSize = QSize(16, 16)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.encodeButton = QtWidgets.QPushButton(self.centralwidget)
        self.encodeButton.setGeometry(QtCore.QRect(540, 560, 141, 71))
        self.encodeButton.setFlat(False)
        self.encodeButton.setObjectName("encodeButton")
        

        self.videoScreen1 = QVideoWidget(self.centralwidget)
        self.videoScreen1.setGeometry(QtCore.QRect(20, 190, 651, 331))
        self.videoScreen1.setObjectName("videoScreen1")
        self.videoScreen2 = QVideoWidget(self.centralwidget)
        self.videoScreen2.setGeometry(QtCore.QRect(730, 190, 621, 331))
        self.videoScreen2.setObjectName("videoScreen2")

        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(870, 0, 481, 181))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.sourceInput = QtWidgets.QLineEdit(self.frame)
        self.sourceInput.setObjectName("sourceInput")
        self.horizontalLayout.addWidget(self.sourceInput)
        self.browseButton1 = QtWidgets.QPushButton(self.frame)
        self.browseButton1.setObjectName("browseButton1")
        self.horizontalLayout.addWidget(self.browseButton1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.DestInput = QtWidgets.QLineEdit(self.frame)
        self.DestInput.setObjectName("DestInput")
        self.horizontalLayout_2.addWidget(self.DestInput)
        self.browseButton2 = QtWidgets.QPushButton(self.frame)
        self.browseButton2.setObjectName("browseButton2")
        self.horizontalLayout_2.addWidget(self.browseButton2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.outputName = QtWidgets.QLineEdit(self.frame)
        self.outputName.setObjectName("outputName")
        self.horizontalLayout_3.addWidget(self.outputName)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_4.addWidget(self.label_10)
        self.decodedPathInput = QtWidgets.QLineEdit(self.frame)
        self.decodedPathInput.setObjectName("decodedPathInput")
        self.horizontalLayout_4.addWidget(self.decodedPathInput)
        self.browseButton3 = QtWidgets.QPushButton(self.frame)
        self.browseButton3.setObjectName("browseButton3")
        self.horizontalLayout_4.addWidget(self.browseButton3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_5.addWidget(self.label_11)
        self.decodedName = QtWidgets.QLineEdit(self.frame)
        self.decodedName.setObjectName("decodedName")
        self.horizontalLayout_5.addWidget(self.decodedName)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(70, 660, 621, 151))
        self.textBrowser.setObjectName("textBrowser")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 261, 111))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.layoutWidget = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 0, 237, 100))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)

        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)

        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setTextFormat(QtCore.Qt.AutoText)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)

        self.playButton1 = QtWidgets.QPushButton(self.centralwidget)
        self.playButton1.setGeometry(QtCore.QRect(290, 530, 93, 28))
        self.playButton1.setFixedHeight(24)
        self.playButton1.setIconSize(btnSize)
        self.playButton1.setIcon(self.style().standardIcon(QStyle.SP_MediaPlay))
        self.playButton1.setObjectName("playButton1")
        
        self.playButton2 = QtWidgets.QPushButton(self.centralwidget)
        self.playButton2.setGeometry(QtCore.QRect(1010, 530, 93, 28))
        self.playButton2.setFixedHeight(24)
        self.playButton2.setIconSize(btnSize)
        self.playButton2.setIcon(self.style().standardIcon(QStyle.SP_MediaPlay))
        self.playButton2.setObjectName("playButton2")

        self.decodeButton = QtWidgets.QPushButton(self.centralwidget)
        self.decodeButton.setGeometry(QtCore.QRect(720, 560, 141, 71))
        self.decodeButton.setFlat(False)
        
        self.decodeButton.setObjectName("decodeButton")

        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(720, 660, 621, 151))
        self.textBrowser_2.setObjectName("textBrowser_2")

        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(80, 630, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")

        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(720, 640, 181, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")

        self.dispButton = QtWidgets.QPushButton(self.centralwidget)
        self.dispButton.setGeometry(QtCore.QRect(1210, 620, 131, 28))
        self.dispButton.setObjectName("dispButton")

        self.huffButton = QtWidgets.QPushButton(self.centralwidget)
        self.huffButton.setGeometry(QtCore.QRect(1042, 620, 141, 28))
        self.huffButton.setObjectName("huffButton")

        self.decodedSize = QtWidgets.QLabel(self.centralwidget)
        self.decodedSize.setGeometry(QtCore.QRect(1150, 530, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.decodedSize.setFont(font)
        self.decodedSize.setObjectName("decodedSize")

        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(20, 170, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")

        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(730, 170, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")

        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(540, 10, 154, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(281, 52, 125, 103))
        self.widget.setObjectName("widget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_13 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_6.addWidget(self.label_13)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.DCTRadio = QtWidgets.QRadioButton(self.widget)
        self.DCTRadio.setObjectName("DCTRadio")
        self.verticalLayout_5.addWidget(self.DCTRadio)
        self.FFTRadio = QtWidgets.QRadioButton(self.widget)
        self.FFTRadio.setObjectName("FFTRadio")
        self.verticalLayout_5.addWidget(self.FFTRadio)
        self.DSTRadio = QtWidgets.QRadioButton(self.widget)
        self.DSTRadio.setObjectName("DSTRadio")
        self.verticalLayout_5.addWidget(self.DSTRadio)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(500, 40, 231, 51))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_14 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_6.addWidget(self.label_14)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.yChromRadio = QtWidgets.QRadioButton(self.widget1)
        self.yChromRadio.setObjectName("yChromRadio")
        self.verticalLayout_3.addWidget(self.yChromRadio)
        self.yLumRadio = QtWidgets.QRadioButton(self.widget1)
        self.yLumRadio.setObjectName("yLumRadio")
        self.verticalLayout_3.addWidget(self.yLumRadio)
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)

        self.widget2 = QtWidgets.QWidget(self.centralwidget)
        self.widget2.setGeometry(QtCore.QRect(500, 100, 224, 51))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_15 = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_7.addWidget(self.label_15)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.cChromRadio = QtWidgets.QRadioButton(self.widget2)
        self.cChromRadio.setObjectName("cChromRadio")
        self.verticalLayout_4.addWidget(self.cChromRadio)
        self.cLumRadio = QtWidgets.QRadioButton(self.widget2)
        self.cLumRadio.setObjectName("cLumRadio")
        self.verticalLayout_4.addWidget(self.cLumRadio)
        self.horizontalLayout_7.addLayout(self.verticalLayout_4)

        self.customButton = QtWidgets.QPushButton(self.centralwidget)
        self.customButton.setGeometry(QtCore.QRect(740, 70, 101, 51))
        self.customButton.setObjectName("customButton")

        self.oriSize = QtWidgets.QLabel(self.centralwidget)
        self.oriSize.setGeometry(QtCore.QRect(20, 530, 270, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.oriSize.setFont(font)
        self.oriSize.setObjectName("oriSize")
        self.encSize = QtWidgets.QLabel(self.centralwidget)
        self.encSize.setGeometry(QtCore.QRect(20, 570, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.encSize.setFont(font)
        self.encSize.setObjectName("encSize")

        self.helpButton = QtWidgets.QPushButton(self.centralwidget)
        self.helpButton.setGeometry(QtCore.QRect(10, 110, 93, 28))
        self.helpButton.setObjectName("helpButton")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1378, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        #Setting radio button
        self.DCTRadio.setChecked(True)
        self.yLumRadio.setChecked(True)
        self.cChromRadio.setChecked(True)
        self.dispButton.setEnabled(False)
        self.huffButton.setEnabled(False)
        self.playButton1.setEnabled(False)
        self.playButton2.setEnabled(False)
        self.decodeButton.setEnabled(True)
        self.encodeButton.setEnabled(True)

        self.centralwidget.setStyleSheet('background-color: lightgreen')
        self.sourceInput.setStyleSheet('background-color: white;border: 1px solid black;')
        self.DestInput.setStyleSheet('background-color: white;border: 1px solid black;')
        self.decodedPathInput.setStyleSheet('background-color: white;border: 1px solid black;')
        self.outputName.setStyleSheet('background-color: white;border: 1px solid black;')
        self.decodedName.setStyleSheet('background-color: white;border: 1px solid black;')
        self.browseButton1.setStyleSheet('background-color: lightgrey;')
        self.browseButton2.setStyleSheet('background-color: lightgrey;')
        self.browseButton3.setStyleSheet('background-color: lightgrey;')
        self.videoScreen1.setStyleSheet('background-color: black;')
        self.videoScreen2.setStyleSheet('background-color: black;')
        self.playButton1.setStyleSheet('background-color: none;')
        self.playButton2.setStyleSheet('background-color: none;')
        self.encodeButton.setStyleSheet('background-color: yellow;')
        self.decodeButton.setStyleSheet('background-color: yellow;')
        self.huffButton.setStyleSheet('background-color: none;')
        self.dispButton.setStyleSheet('background-color: none;')
        self.textBrowser.setStyleSheet('background-color: none;')
        self.textBrowser_2.setStyleSheet('background-color: none;')
        self.helpButton.setStyleSheet('background-color: lightyellow;')
        self.customButton.setStyleSheet('background-color: cyan;')
        self.retranslateUi(MainWindow)
        
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.encodeButton.setText(_translate("MainWindow", "Encode"))
        self.label_2.setText(_translate("MainWindow", "Source File Path        "))
        self.browseButton1.setText(_translate("MainWindow", "Browse"))
        self.label_3.setText(_translate("MainWindow", "Encoded File Folder   "))
        self.browseButton2.setText(_translate("MainWindow", "Browse"))
        self.label_4.setText(_translate("MainWindow", "Encoded File Name    "))
        self.label_10.setText(_translate("MainWindow", "Decoded Video Folder"))
        self.browseButton3.setText(_translate("MainWindow", "Browse"))
        self.label_11.setText(_translate("MainWindow", "Decoded Video Name "))
        self.label.setText(_translate("MainWindow", "Kelompok 2 - Video Encoding \n"
"Made by :"))
        self.label_5.setText(_translate("MainWindow", "Ervin Halimsurya  - 1806195173"))
        self.label_6.setText(_translate("MainWindow", "Jonathan Richard - 1806147930"))
        self.decodeButton.setText(_translate("MainWindow", "Decode"))
        self.label_7.setText(_translate("MainWindow", "Terminal"))
        self.label_8.setText(_translate("MainWindow", "Encoded file Viewer"))
        self.dispButton.setText(_translate("MainWindow", "Display Encoded File"))
        self.huffButton.setText(_translate("MainWindow", "Display Huffman Table"))
        self.decodedSize.setText(_translate("MainWindow", "Video Size :"))
        self.label_9.setText(_translate("MainWindow", "Source"))
        self.label_12.setText(_translate("MainWindow", "Decoded"))
        self.label_13.setText(_translate("MainWindow", "Transform Method"))
        self.DCTRadio.setText(_translate("MainWindow", "DCT"))
        self.FFTRadio.setText(_translate("MainWindow", "DFT"))
        self.label_16.setText(_translate("MainWindow", "Quantization Method"))
        self.label_14.setText(_translate("MainWindow", "Y Component"))
        self.yChromRadio.setText(_translate("MainWindow", "Chrominance"))
        self.yLumRadio.setText(_translate("MainWindow", "Luminance"))
        self.label_15.setText(_translate("MainWindow", "CbCr Component"))
        self.cChromRadio.setText(_translate("MainWindow", "Chrominance"))
        self.cLumRadio.setText(_translate("MainWindow", "Luminance"))
        self.customButton.setText(_translate("MainWindow", "Custom\n"
"Quantization"))
        self.DSTRadio.setText(_translate("MainWindow", "DST"))
        self.oriSize.setText(_translate("MainWindow", "Original Video Size :"))
        self.encSize.setText(_translate("MainWindow", "Encoded File Size :"))
        self.helpButton.setText(_translate("MainWindow", "Help"))
from PyQt5.QtMultimediaWidgets import QVideoWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
